#!/usr/bin/env python3
"""PaperOffice AI — AI-powered document generation (Create from Content)

Usage:
    export PAPEROFFICE_API_KEY=po_sk_xxx
    python3 example.py 42                        # workspace_id
    python3 example.py 42 "Monthly Report"       # with custom title
"""
import os
import sys
import json
import requests

api_base = "https://api.paperoffice.ai/latest"
api_key = os.environ.get("PAPEROFFICE_API_KEY", "")


def create_from_content(
    content: str,
    workspace_id: int,
    title: str = "Generated Document",
    content_type: str = "markdown",
    language: str = "en",
    token: str = api_key,
) -> dict:
    """Generates a PDF from Markdown or HTML content."""
    if not token:
        raise ValueError("PAPEROFFICE_API_KEY not set")

    payload = {
        "content": content,
        "content_type": content_type,
        "output_format": "pdf",
        "title": title,
        "workspace_id": workspace_id,
        "language": language,
    }

    response = requests.post(
        f"{api_base}/document_generation/create-from-content",
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        json=payload,
    )
    response.raise_for_status()
    return response.json()


def download_document(url: str, output_path: str, token: str = api_key):
    """Downloads the generated document."""
    response = requests.get(
        url,
        headers={"Authorization": f"Bearer {token}"},
        stream=True,
    )
    response.raise_for_status()
    with open(output_path, "wb") as f:
        for chunk in response.iter_content(chunk_size=8192):
            f.write(chunk)
    print(f"  Saved: {output_path}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("Usage: python3 example.py <workspace_id> [title]")

    workspace_id = int(sys.argv[1])
    title = sys.argv[2] if len(sys.argv) > 2 else "Generated Document"

    content = f"""# {title}

## Summary

This document was generated via the PaperOffice AI Document Generation API.

- **Date:** 2026-04-08
- **Generated by:** API example script

## Content

Lorem ipsum dolor sit amet, consectetur adipiscing elit. This is an example
document demonstrating the create-from-content endpoint.
"""

    print(f"-> Generating document: {title}")
    result = create_from_content(content, workspace_id, title=title)

    if result.get("status") == "success":
        doc = result.get("document", {})
        print(f"  Download URL: {doc.get('download_url', '-')}")
        print(f"  Format:       {doc.get('format', '-')}")
        print(f"  Pages:        {doc.get('pages', '-')}")
        print(f"  POFID:        {doc.get('pofid', '-')}")

        download_url = doc.get("download_url")
        if download_url:
            download_document(download_url, f"generated.pdf")
    else:
        print("Error:", json.dumps(result, indent=2))
