#!/usr/bin/env bash
# PaperOffice AI — AI-powered document generation (Create from Content)
set -euo pipefail

api_base="https://api.paperoffice.ai/latest"
api_key="${PAPEROFFICE_API_KEY:?Please set PAPEROFFICE_API_KEY}"

workspace_id="${1:?Please provide workspace_id as first argument}"
title="${2:-Generated Document}"

content="# ${title}

## Summary

This document was generated via the PaperOffice AI Document Generation API.

- **Date:** $(date +%Y-%m-%d)
- **Generated by:** API example script

## Content

Lorem ipsum dolor sit amet, consectetur adipiscing elit. This is an example
document demonstrating the create-from-content endpoint."

echo "-> Generating document: ${title}"

response=$(curl -s -X POST "${api_base}/document_generation/create-from-content" \
  -H "Authorization: Bearer ${api_key}" \
  -H "Content-Type: application/json" \
  -d "$(python3 -c "
import json
print(json.dumps({
    'content': '''${content}''',
    'content_type': 'markdown',
    'output_format': 'pdf',
    'title': '${title}',
    'workspace_id': ${workspace_id},
    'language': 'en'
}))
")")

echo "${response}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
if data.get('status') != 'success':
    print('Error:', json.dumps(data, indent=2))
    sys.exit(1)
doc = data.get('document', {})
print(f'  Download URL: {doc.get(\"download_url\", \"-\")}')
print(f'  Format:       {doc.get(\"format\", \"-\")}')
print(f'  Pages:        {doc.get(\"pages\", \"-\")}')
print(f'  POFID:        {doc.get(\"pofid\", \"-\")}')
"
