#!/usr/bin/env node
/** PaperOffice AI — AI-powered document generation (Create from Content) */
import { writeFileSync } from "node:fs";

const api_base = "https://api.paperoffice.ai/latest";
const api_key = process.env.PAPEROFFICE_API_KEY || "";

async function create_from_content(content, workspace_id, title = "Generated Document", token = api_key) {
  if (!token) throw new Error("PAPEROFFICE_API_KEY not set");

  const response = await fetch(`${api_base}/document_generation/create-from-content`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      content,
      content_type: "markdown",
      output_format: "pdf",
      title,
      workspace_id,
      language: "en",
    }),
  });

  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  return response.json();
}

async function download_document(url, output_path, token = api_key) {
  const response = await fetch(url, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!response.ok) throw new Error(`Download failed: HTTP ${response.status}`);

  const buffer = Buffer.from(await response.arrayBuffer());
  writeFileSync(output_path, buffer);
  console.log(`  Saved: ${output_path}`);
}

(async () => {
  const workspace_id = parseInt(process.argv[2], 10);
  if (isNaN(workspace_id)) {
    console.error("Usage: node example.js <workspace_id> [title]");
    process.exit(1);
  }

  const title = process.argv[3] || "Generated Document";

  const content = `# ${title}

## Summary

This document was generated via the PaperOffice AI Document Generation API.

- **Date:** 2026-04-08
- **Generated by:** API example script

## Content

Lorem ipsum dolor sit amet, consectetur adipiscing elit. This is an example
document demonstrating the create-from-content endpoint.
`;

  console.log(`-> Generating document: ${title}`);
  const data = await create_from_content(content, workspace_id, title);

  if (data.status === "success") {
    const doc = data.document || {};
    console.log(`  Download URL: ${doc.download_url ?? "-"}`);
    console.log(`  Format:       ${doc.format ?? "-"}`);
    console.log(`  Pages:        ${doc.pages ?? "-"}`);
    console.log(`  POFID:        ${doc.pofid ?? "-"}`);

    if (doc.download_url) {
      await download_document(doc.download_url, "generated.pdf");
    }
  } else {
    console.error("Error:", JSON.stringify(data, null, 2));
  }
})();
